### ISSUE TITLE
Arduino based geiger counter code

### ISSUE THREAD

**Issue by tekelectron** [RobertGawron/GeigerMullerCounter#108]
Sorry to bother you but I built the Arduino based geiger counter using a nokia 5110 display but it looks like the software has since been removed from github under this tree

Would you be willing to send me the source code or add it to a repository? 

Thank you
James

Projecy: https://robertgawron.blogspot.com/2016/07/using-arduino-to-process-data-from_24.html

**Comment by RobertGawron** [comment]
Hi James, 

I think this was the latest version:

[GeigerMullerCounter.zip](https://github.com/RobertGawron/GeigerMullerCounter/files/8268749/GeigerMullerCounter.zip)

Note that you will need to install Adafruit_GFX and Adafruit_PCD8544 in Arduino IDE via Sketch -> Include Library -> Manage  libraries.

-Robert

**Comment by tekelectron** [comment]
Hi Robert

Thank you so much! Works fine with the libraries as you suggested.

Thanks again
James
