### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by MatejKovacic** [RobertGawron/GeigerMullerCounter#12]
Hi,

sorry to bother you here. I was looking for your contact on your website, but there is none.

Anyway, I found your project very interesting. In fact, I have one SBM-20 Geiger tube (I planned to build my own Geiger counter a few years ago, but never finished it). What is the difference between this and your STS-5 tube?

Also, where did you find metallic holders for lamps? Do you have a figure (picture of a prototype) of the circuit and list of required materials?

And the final question - did you plan to make a digital Geiger counter based on Raspberry Pi?

P. S. My e-mail can be found here: https://keyserver.ubuntu.com/pks/lookup?op=get&search=0xBEA5286DA9CF4A88

Regards,
M.

**Comment by RobertGawron** [comment]
One can be replaced by other, they are pretty much the same.

Holders are just regular fuses holders, Russians were smart and mechanically designed theirs tubes to be able to place them in holders popular in civil equipment - stocks of popular parts are easier to find in case of e.g. war.

Circuit is presented here: https://robertgawron.blogspot.com/2015/02/homemade-geigermuller-counter-part-i.html

I don't plan at the moment, but there is version for Aurduino:
https://robertgawron.blogspot.com/2016/07/using-arduino-to-process-data-from_24.html

TBH its histograms works quite awful, but rest of it is ok.

Regards,
Bob
