### ISSUE TITLE
geiger with stm32

### ISSUE THREAD

**Issue by 123LY321** [RobertGawron/GeigerMullerCounter#56]
Sorry to bother you, but I want to make a geiger detection suite for the main chip using stm32. Can I get a circuit diagram from you? Thank you

**Comment by RobertGawron** [comment]
Hi,

you need a diagram of the gieger counter or diagram how to connect it and LCD to STM32 eval board?

If the first one, you can open the project files in hardware directory using KiCAD and you will have the diagram.

-Robert
