### ISSUE TITLE
Zener diode details

### ISSUE THREAD

**Issue by piotrkochan** [RobertGawron/GeigerMullerCounter#89]
Please provide what zener diode should be used 

![image](https://user-images.githubusercontent.com/5632761/96258913-0ca04e00-0fbd-11eb-9d1b-e49d874b0366.png)

**Comment by RobertGawron** [comment]
Hello this diode is to protect input of op-amp if  voltage spike from GM tube would be for some reason too big and it's just in case.

Something around op-amp's power supply value would be good, so 5V.
